### ISSUE TITLE
Create second version for L4

### ISSUE THREAD

**Issue by RomainLanz** [mkoterle/Roleable#1]
Hey,

You force all of your tag and branch for L5, could you create a tag/branch for L4 ?

Thx!

**Comment by martink635** [comment]
Will make a branch that is compatible with L4!

**Comment by RomainLanz** [comment]
Thanks!

**Comment by RomainLanz** [comment]
Ping @mkoterle

**Comment by martink635** [comment]
I Just made a new release with a tag 0.9.0, which requires Laravel 4. I do not have time to test if it actually works until Saturday, please test and post back if I need to change anything. I think everything should be ok!

**Comment by RomainLanz** [comment]
I will test that this afternoon, thanks.

**Comment by RomainLanz** [comment]
All seems to work fine.

**Comment by RomainLanz** [comment]
When I launch migration for this package I get this error.

```
[Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1005 Can't create table 'cpnves.#sql-45e_38' (errno: 150) (SQL: alter table `role_user` add constraint role_user_user_id_foreign foreign key (`user_id`) references `us
  ers` (`id`) on delete cascade)
```

**Comment by RomainLanz** [comment]
I found the solution. On the configuration file, you are according that user_id is a UUID, but in default it's not.

**Comment by martink635** [comment]
No, since laravel doesn't have uuid support. I will accept the PR and change it to id :)
